; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=pdcpu32 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=PD32IF %s

declare float @llvm.minnum.f32(float, float)

define float @clip(float %min, float %max, float %val) nounwind {
; PD32IF-LABEL: clip:
; PD32IF:       # %bb.0:
; PD32IF-NEXT:    fbgt f10, f12, .LBB0_2
; PD32IF-NEXT:  # %bb.1:
; PD32IF-NEXT:    mov f10, f12
; PD32IF-NEXT:  .LBB0_2:
; PD32IF-NEXT:    fbgt f11, f10, .LBB0_4
; PD32IF-NEXT:  # %bb.3:
; PD32IF-NEXT:    mov f10, f11
; PD32IF-NEXT:  .LBB0_4:
; PD32IF-NEXT:  eoi

entry:
  %cmp3 = fcmp fast olt float %val, %min
  %. = select i1 %cmp3, float %min, float %val
  %0 = tail call fast float @llvm.minnum.f32(float %., float %max)
  ret float %0
}
