; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=pdcpu32 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=PD32IF %s

; These tests are each targeted at a particular PD-CPU control instruction. Most
; other files in this folder exercise LLVM IR instructions that don't directly
; match a PD-CPU instruction.

define void @eoi() nounwind {
; PD32IF-LABEL: eoi:
; PD32IF:       # %bb.0:
; PD32IF-NEXT:    #APP
; PD32IF-NEXT:    eoi
; PD32IF-NEXT:    #NO_APP
;
  call void asm sideeffect "eoi", "~{dirflag},~{fpsr},~{flags}"() #1
  ret void
}
