; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=pdcpu32 -mattr=+f -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=PD32IF %s

; These tests are focussed on testing the FADD instruction.

define float @fadd_2(float %a, float %b) nounwind {
; PD32IF-LABEL: fadd_2:
; PD32IF:       # %bb.0:
; PD32IF-NEXT:    fadd f10, f10, f11
;
  %1 = fadd float %a, %b
  ret float %1
}

define float @fadd_3(float %a, float %b, float %c) nounwind {
; PD32IF-LABEL: fadd_3:
; PD32IF:       # %bb.0:
; PD32IF-NEXT:    fadd f1, f10, f11
; PD32IF-NEXT:    fadd f10, f1, f12
;
  %add = fadd float %a, %b
  %add1 = fadd float %add, %c
  ret float %add1
}
